[package]
name = "gdb-mcp"
version = "0.1.0"
edition = "2024"

[dependencies]
rmcp = { version = "0.1", features = ["server"] }
tokio = { version = "1.44", features = ["io-std", "process"] }
serde = { version = "1.0", features = ["derive"] }
